free:
  message_limit_per_day: 5
  max_question_length: 100
  export_conversation: false
  image_model: false
  image_count: 0
basic:
  message_limit_per_day: 15
  max_question_length: 300
  export_conversation: false
  image_model: false
  image_count: 0
standard:
  message_limit_per_day: 30
  max_question_length: 300
  export_conversation: true
  image_model: true
  image_count: 10
advanced:
  message_limit_per_day: 999
  max_question_length: 4000
  export_conversation: true
  image_model: true
  image_count: 50
  can_invite_people: true
