free:
  message_limit_per_day: 2
  max_question_length: 100
  export_conversation: false
  image_model: false
basic:
  message_limit_per_day: 10
  max_question_length: 300
  export_conversation: false
  image_model: false
advanced:
  message_limit_per_day: 999
  max_question_length: 1000
  export_conversation: true
  image_model: true
